### ISSUE TITLE
Website URL must contain "https://www." during conversion.

### ISSUE THREAD

**Issue by KRHero03** [RajatSvN/URL-Shortener#1]
Hi, I found that when you enter the URL name directly, suppose, "facebook.com" as input, it will convert it into shortened URL but when the shortened URL is used, it won't redirect to the website "facebook.com" , instead, it gets redirected to "smlr.ml/facebook.com" which doesn't exist and eventually gives 404 Not Found error. 
Seems like a problem in index.php. Or you can format the URL so that it always contains the above prefix.

**Comment by RajatSvN** [comment]
I have fixed the issue #1 @KRHero03 Thanks for pointing out!
